export const ICONS = {
  activity: 'lucide:activity',
  alertTriangle: 'lucide:alert-triangle',
  arrowUpRight: 'lucide:arrow-up-right',
  bot: 'lucide:bot',
  bookOpen: 'lucide:book-open',
  briefcase: 'lucide:briefcase',
  calendar: 'lucide:calendar',
  checkCircle: 'lucide:check-circle',
  checkSquare: 'lucide:check-square',
  clipboard: 'lucide:clipboard',
  clock: 'lucide:clock',
  close: 'lucide:x',
  closeCircle: 'lucide:x-circle',
  eye: 'lucide:eye',
  eyeOff: 'lucide:eye-off',
  fileText: 'lucide:file-text',
  flame: 'lucide:flame',
  graduationCap: 'lucide:graduation-cap',
  hand: 'lucide:hand',
  hourglass: 'lucide:hourglass',
  inbox: 'lucide:inbox',
  layoutGrid: 'lucide:layout-grid',
  lightbulb: 'lucide:lightbulb',
  lock: 'lucide:lock',
  logOut: 'lucide:log-out',
  megaphone: 'lucide:megaphone',
  monitor: 'lucide:monitor',
  palette: 'lucide:palette',
  panelClose: 'lucide:chevrons-right',
  panelOpen: 'lucide:chevrons-left',
  rocket: 'lucide:rocket',
  rotateCcw: 'lucide:rotate-ccw',
  search: 'lucide:search',
  settings: 'lucide:settings',
  shield: 'lucide:shield',
  smartphone: 'lucide:smartphone',
  sparkles: 'lucide:sparkles',
  star: 'lucide:star',
  stopwatch: 'lucide:stopwatch',
  target: 'lucide:target',
  trendingUp: 'lucide:trending-up',
  trophy: 'lucide:trophy',
  user: 'lucide:user',
  users: 'lucide:users',
} as const

export type IconName = typeof ICONS[keyof typeof ICONS]
