import type { RouteRecordRaw } from 'vue-router'
import AppLayout from '@/layouts/AppLayout.vue'
import { UserRole } from '@/types'

export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'landing',
    component: () => import('@/views/HomeView.vue'),
    meta: { title: '首页', public: true },
  },
  {
    path: '/app/home',
    name: 'app-home',
    component: () => import('@/views/HomeView.vue'),
    meta: { title: '首页', public: true, allowAuthenticated: true },
  },
  {
    path: '/login',
    name: 'login',
    component: () => import('@/views/LoginView.vue'),
    meta: { title: '登录', public: true },
  },
  {
    path: '/app',
    component: AppLayout,
    meta: { requiresAuth: true },
    redirect: '/app/dashboard',
    children: [
      {
        path: 'dashboard',
        name: 'dashboard',
        component: () => import('@/views/DashboardView.vue'),
        meta: { title: '面板', requiresAuth: true },
      },
      {
        path: 'student/learning',
        name: 'student-learning',
        component: () => import('@/views/student/LearningCenter.vue'),
        meta: { title: '学习中心', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/knowledge-graph',
        name: 'student-knowledge-graph',
        component: () => import('@/views/student/KnowledgeExplorer.vue'),
        meta: { title: '知识图谱', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/course/:id',
        name: 'student-course-detail',
        component: () => import('@/views/student/CourseWorkspace.vue'),
        meta: { title: '课程工作台', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
        redirect: { name: 'student-course-tasks' },
        children: [
          {
            path: 'tasks',
            name: 'student-course-tasks',
            component: () => import('@/views/student/CourseTasks.vue'),
            meta: { title: '课程任务', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'chapters',
            name: 'student-course-chapters',
            component: () => import('@/views/student/CourseChapters.vue'),
            meta: { title: '课程章节', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'discuss',
            name: 'student-course-discuss',
            component: () => import('@/views/student/CourseDiscuss.vue'),
            meta: { title: '课程讨论', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'homework',
            name: 'student-course-homework',
            component: () => import('@/views/student/CourseHomework.vue'),
            meta: { title: '课程作业', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'exam',
            name: 'student-course-exam',
            component: () => import('@/views/student/CourseExam.vue'),
            meta: { title: '课程考试', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'resources',
            name: 'student-course-resources',
            component: () => import('@/views/student/CourseResources.vue'),
            meta: { title: '课程资料', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'wrongbook',
            name: 'student-course-wrongbook',
            component: () => import('@/views/student/CourseWrongbook.vue'),
            meta: { title: '课程错题集', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'records',
            name: 'student-course-records',
            component: () => import('@/views/student/CourseRecords.vue'),
            meta: { title: '课程学习记录', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
          {
            path: 'review',
            name: 'student-course-review',
            component: () => import('@/views/student/CourseReview.vue'),
            meta: { title: '课程回顾', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
          },
        ],
      },
      {
        path: 'student/skills',
        name: 'student-skills',
        component: () => import('@/views/student/SkillManagement.vue'),
        meta: { title: '技能管理', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/ai-assistant',
        name: 'student-ai-assistant',
        component: () => import('@/views/student/AIAssistant.vue'),
        meta: { title: 'AI助手', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/visualization',
        name: 'student-visualization',
        redirect: '/app/student/report',
      },
      {
        path: 'student/test-visualization',
        name: 'student-test-visualization',
        component: () => import('@/views/student/TestVisualization.vue'),
        meta: { title: '可视化测试', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/report',
        name: 'student-report',
        component: () => import('@/views/student/Report.vue'),
        meta: { title: '学习报告', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/career',
        name: 'student-career',
        component: () => import('@/views/student/CareerCenter.vue'),
        meta: { title: '职业发展中心', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'student/career-analysis',
        name: 'student-career-analysis',
        component: () => import('@/views/student/CareerAnalysis.vue'),
        meta: { title: '职业分析', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER], immersive: true },
      },
      {
        path: 'student/career-navigation',
        name: 'student-career-navigation',
        component: () => import('@/views/student/CareerNavigation.vue'),
        meta: { title: '职途导航', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER], immersive: true },
      },
      {
        path: 'student/resume-builder',
        name: 'student-resume-builder',
        component: () => import('@/views/student/ResumeBuilder.vue'),
        meta: { title: '快速制作简历', requiresAuth: true, roles: [UserRole.STUDENT], immersive: true },
      },
      {
        path: 'student/career-report',
        name: 'student-career-report',
        component: () => import('@/views/student/CareerReport.vue'),
        meta: { title: '职业生涯发展报告', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER], immersive: true },
      },
      {
        path: 'student/career-ability',
        name: 'career-ability',
        component: () => import('@/views/student/CareerAbilityShell.vue'),
        meta: { title: '职业能力图谱', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER], immersive: true },
      },
      {
        path: 'student/course-system',
        name: 'course-system',
        component: () => import('@/views/student/CourseSystemGraph.vue'),
        meta: { title: '课程体系', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER], immersive: true },
      },
      {
        path: 'student/career-ability/graph',
        name: 'career-ability-graph',
        redirect: to => ({ name: 'career-ability', query: to.query }),
      },
      {
        path: 'student/career-ability/dual',
        name: 'career-ability-dual',
        redirect: to => ({ name: 'career-ability', query: to.query }),
      },
      {
        path: 'student/career-ability/workspace',
        name: 'career-ability-workspace',
        redirect: to => ({ name: 'career-ability', query: to.query }),
      },
      {
        path: 'student/career-ability-graph',
        name: 'student-career-ability-graph',
        redirect: to => ({ name: 'career-ability', query: to.query }),
      },
      {
        path: 'student/settings',
        name: 'student-settings',
        component: () => import('@/views/student/Settings.vue'),
        meta: { title: '个人设置', requiresAuth: true, roles: [UserRole.STUDENT, UserRole.TEACHER] },
      },
      {
        path: 'teacher/courses',
        name: 'teacher-courses',
        component: () => import('@/views/teacher/Courses.vue'),
        meta: { title: '课程管理', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'teacher/course/edit/:id?',
        name: 'teacher-course-edit',
        component: () => import('@/views/teacher/CourseEdit.vue'),
        meta: { title: '编辑课程', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'teacher/students',
        name: 'teacher-students',
        component: () => import('@/views/teacher/Students.vue'),
        meta: { title: '学生管理', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'teacher/grading',
        name: 'teacher-grading',
        component: () => import('@/views/teacher/Grading.vue'),
        meta: { title: '作业批改', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'teacher/class-report',
        name: 'teacher-class-report',
        component: () => import('@/views/teacher/ClassReport.vue'),
        meta: { title: '班级报告', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'teacher/monitoring',
        name: 'teacher-monitoring',
        component: () => import('@/views/teacher/Monitoring.vue'),
        meta: { title: '学情监控', requiresAuth: true, role: UserRole.TEACHER },
      },
      {
        path: 'admin/users',
        name: 'admin-users',
        component: () => import('@/views/admin/Users.vue'),
        meta: { title: '用户管理', requiresAuth: true, role: UserRole.ADMIN },
      },
      {
        path: 'admin/content-review',
        name: 'admin-content-review',
        component: () => import('@/views/admin/ContentReview.vue'),
        meta: { title: '内容审核', requiresAuth: true, role: UserRole.ADMIN },
      },
      {
        path: 'admin/system-stats',
        name: 'admin-system-stats',
        component: () => import('@/views/admin/SystemStats.vue'),
        meta: { title: '系统监控', requiresAuth: true, role: UserRole.ADMIN },
      },
      {
        path: 'courses',
        name: 'courses',
        component: () => import('@/views/course/CoursesView.vue'),
        meta: { title: '课程列表', requiresAuth: true },
      },
      {
        path: 'exams',
        name: 'exams',
        component: () => import('@/views/course/ExamsView.vue'),
        meta: { title: '考试', requiresAuth: true },
      },
      {
        path: 'wrongbook',
        name: 'wrongbook',
        component: () => import('@/views/course/WrongBookView.vue'),
        meta: { title: '错题本', requiresAuth: true },
      },
      {
        path: 'messages',
        name: 'messages',
        component: () => import('@/views/course/MessagesView.vue'),
        meta: { title: '消息', requiresAuth: true },
      },
      {
        path: 'notes',
        name: 'notes',
        component: () => import('@/views/course/NotesView.vue'),
        meta: { title: '笔记', requiresAuth: true },
      },
      {
        path: 'profile',
        name: 'profile',
        component: () => import('@/views/ProfileView.vue'),
        meta: { title: '个人中心', requiresAuth: true },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'not-found',
    component: () => import('@/views/NotFoundView.vue'),
    meta: { title: '页面未找到', public: true },
  },
]
